# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chithub < Formula
  desc "Manage every git repo in a folder — commit, push, pull and review in one place."
  homepage "https://github.com/Amirhat/ChitHub"
  version "0.1.2"
  license "MIT"

  on_macos do
    url "https://github.com/Amirhat/ChitHub/releases/download/v0.1.2/chithub_0.1.2_darwin_all.tar.gz"
    sha256 "4f6a401d52ac174fd75397be91dca6fa292fe2e2360a96c987b95233bbec5bcf"

    define_method(:install) do
      bin.install "chithub"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Amirhat/ChitHub/releases/download/v0.1.2/chithub_0.1.2_linux_amd64.tar.gz"
      sha256 "05c4135701c4f582cda2e4ee69e1166e158d20c72ae879e1567c70266a2ab36a"
      define_method(:install) do
        bin.install "chithub"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Amirhat/ChitHub/releases/download/v0.1.2/chithub_0.1.2_linux_arm64.tar.gz"
      sha256 "5aaf39449b1ff3aefe1042fa3ffb6ae33a93ee87ac835b1c67b21371451a4597"
      define_method(:install) do
        bin.install "chithub"
      end
    end
  end

  test do
    system "#{bin}/chithub", "-version"
  end
end
